---
- hosts: servers
  become: true
  tasks:
    - name: Actualizar la caché de software de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar Cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo
      file:
        path: /home/vagrant/archivo.txt
        state: touch

    - name: Copiar archivos
      copy:
        src: /mnt/c/Users/User/Videos/ansible-practice/mi_archivo.txt
        dest: /home/vagrant/destino.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/carpeta
        state: directory

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario al servidor
      user:
        name: nuevo_usuario
        state: present

    - name: Ejecutar un script en el servidor
      shell: /home/vagrant/scripts/script.sh
